version: "3.9"

services:
  backend:
    build: ./backend                # build Node app from backend folder
    container_name: vastu_backend
    restart: always
    env_file:
      - ./backend/.env              # environment file stored inside backend folder
    expose:                         # expose internal for nginx proxy only
      - "3000"
    networks:
      - vastu_network

  nginx:
    image: nginx:alpine
    container_name: vastu_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - vastu_network

networks:
  vastu_network:
    driver: bridge
