services:
  backend:
    build: .
    container_name: vastu_backend
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3030:3030"
    networks:
      - vastu_network

networks:
  vastu_network:
    driver: bridge
